### PR TITLE
fix some codes for supporting clExport Build on x64

### PR DESCRIPTION
**Pull request by SungJJinKang**
I'm sorry for my previous careless pull request.
I fixed it. I tried to touch codes as little as possible.

And inlined __asm codes can't be build on x64.
I don't know how to deal with it, So I didn't touch it.

### CODE REVIEW

**Comment by SungJJinKang** [comment]
Please comment on this pr, Then I'll fix it.

**Comment by dwilliamson** [comment]
Sorry that's all I can do for now, I'll be back on Tuesday.

**Comment by SungJJinKang** [comment]
I think if change some codes, clexport's output can be portable ( can be read in x86, x64 runtime ). Did you consider that? clscan, clmerge's output looks portable.

**Comment by dwilliamson** [comment]
It can't really be portable unless the `clcpp` types that contain pointers are padded with redundant fields to 64-bits. The final exported data is a memory map: loading simply does a limited set of linear reads followed by a pointer patch up.

Have you had time to address my comments above?

**Comment by SungJJinKang** [comment]
@dwilliamson  Yes. I thought if pointers have redundant padding, it works. Is it bad? Please understand my poor knowledge...

How about my pull request? Is it acceptable?

**Comment by dwilliamson** [comment]
> Yes. I thought if pointers have redundant padding, it works. Is it bad? Please understand my poor knowledge...

It would work, yes. But the `clcpp` API would look quite convoluted as there are a lot of pointers; I don't want to do this.

> How about my pull request? Is it acceptable?

I have left some comments above in the source code itself. Can you see them?

**Review by SungJJinKang — COMMENTED** [review]
add _lzcnt function based on which compiler. add _M_IX86(x86 machine macros) because inlined asm code can't be build on msvc x64

**Comment by SungJJinKang** [comment]
@dwilliamson Nop.. I can't see them. Where is it??

**Comment by SungJJinKang** [comment]
I revert some codes after see your comment. is it right?

**Comment by SungJJinKang** [comment]
> > Yes. I thought if pointers have redundant padding, it works. Is it bad? Please understand my poor knowledge...
> 
> It would work, yes. But the `clcpp` API would look quite convoluted as there are a lot of pointers; I don't want to do this.
> 
> > How about my pull request? Is it acceptable?
> 
> I have left some comments above in the source code itself. Can you see them?

Maybe you're saying about using clcpp:size_type to hold offset
but clExport use size_t to store pointer offset.

I don't know how to deal with this...

**Pull request closed without merging**
